### ISSUE TITLE
PhpParser\Node\Param::$hooks must not be accessed before initialization

### ISSUE THREAD

**Issue by liviuconcioiu** [nikic/PHP-Parser#1024]
I get this error when running Psalm. It wasn't happening with 5.1.0.

PHP-Parser: 5.2.0
Psalm: dev-master#16b24bdc94e052b5ce69fd232a77416a1f6ec3e6

```
Uncaught Error: Typed property PhpParser\Node\Param::$hooks must not be accessed before initialization in \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php:95
Stack trace:
#0 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(215): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Param))
#1 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(98): PhpParser\NodeTraverser->traverseArray(Array)
#2 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(215): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#3 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(98): PhpParser\NodeTraverser->traverseArray(Array)
#4 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(215): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#5 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(98): PhpParser\NodeTraverser->traverseArray(Array)
#6 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(215): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#7 \vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(76): PhpParser\NodeTraverser->traverseArray(Array)
#8 \vendor\vimeo\psalm\src\Psalm\Internal\Provider\StatementsProvider.php(163): PhpParser\NodeTraverser->traverse(Array)
#9 \vendor\vimeo\psalm\src\Psalm\Internal\Scanner\FileScanner.php(44): Psalm\Internal\Provider\StatementsProvider->getStatementsForFile('', 80300, Object(Psalm\Progress\DefaultProgress))
#10 \vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(539): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#11 \vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(767): Psalm\Internal\Codebase\Scanner->scanFile('', Array, true)
#12 \vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(413): Psalm\Internal\Codebase\Scanner->scanAPath(1, '')
#13 \vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(261): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#14 \vendor\vimeo\psalm\src\Psalm\Codebase.php(436): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#15 \vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(501): Psalm\Codebase->scanFiles(1)
#16 \vendor\vimeo\psalm\src\Psalm\Internal\Cli\Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->check('', false)
#17 \vendor\vimeo\psalm\psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#18 \vendor\bin\psalm(119): include('')
#19 {main}
(Psalm dev-master@16b24bdc94e052b5ce69fd232a77416a1f6ec3e6 crashed due to an uncaught Throwable)
```

**Comment by nikic** [comment]
My best guess is that psalm has some kind of cache with serialized ASTs that did not get cleared when updating PHP-Parser.

**Comment by liviuconcioiu** [comment]
It was a cache issue.
