### ISSUE TITLE
Exception on parsing files (with namespace) containing a shebang

### ISSUE THREAD

**Issue by JWZH** [nikic/PHP-Parser#243]
PHP Parser fails to parse PHP file with a namespace that contains a shebang:
```lang=php
$code = <<<CODE
#!/usr/bin/env php
<?php
namespace A;
CODE;

$parser = new PhpParser\Parser(new PhpParser\Lexer);
$nodeDumper = new PhpParser\NodeDumper;
$parser->parse($code);
```
The output of running above code is 
```
PHP Fatal error:  Uncaught exception 'PhpParser\Error' with message 'Namespace declaration statement has to be the very first statement in the script on line 3' in /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:453
Stack trace:
#0 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(409): PhpParser\ParserAbstract->getNamespacingStyle(Array)
#1 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/Parser.php(1050): PhpParser\ParserAbstract->handleNamespaces(Array)
#2 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(242): PhpParser\Parser->reduceRule1()
#3 /home/wjiang/Code/freelancer/production/r.php(13): PhpParser\ParserAbstract->parse('#!/usr/bin/env?...')
#4 {main}
  thrown in /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 453
FATAL: : Uncaught exception 'PhpParser\Error' with message 'Namespace declaration statement has to be the very first statement in the script on line 3' in /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:453
Stack trace:
#0 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(409): PhpParser\ParserAbstract->getNamespacingStyle(Array)
#1 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/Parser.php(1050): PhpParser\ParserAbstract->handleNamespaces(Array)
#2 /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(242): PhpParser\Parser->reduceRule1()
#3 /home/wjiang/Code/freelancer/production/r.php(13): PhpParser\ParserAbstract->parse('#!/usr/bin/env?...')
#4 {main}
  thrown in /home/wjiang/Code/freelancer/production/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 453 via CLI
```
But this code 
```
#!/usr/bin/env php
<?php
namespace A;
```
is legal PHP code as it can be executed by PHP 5.5.

I'm using  the release 1.3.0 version.

**Comment by nikic** [comment]
Thanks for the report, this should be fixed by https://github.com/nikic/PHP-Parser/commit/c4bbc8e236a1f21b2b17cfbf3d46aa6ece69b9f7.
