### ISSUE TITLE
Class constant visibility not supported (PHP 7.1 feature)

### ISSUE THREAD

**Issue by asgrim** [nikic/PHP-Parser#285]
Tried with both `2.1.0` and `dev-master @ 96cbd48`, but the new PHP 7.1 class constant visibility is not supported:

https://wiki.php.net/rfc/class_const_visibility

Failing example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$c = <<<'PHP'
<?php

class Foo
{
    private const PRIVATE_CONST = 0;
}
PHP;


use PhpParser\ParserFactory;
$parser = (new ParserFactory)
    ->create(ParserFactory::PREFER_PHP7);

print_r($parser->parse($c));
```

Error seen running this:

```
PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_CONST, expecting T_FUNCTION on line 5 in /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:280
Stack trace:
#0 /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nclass Fo...')
#1 /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), '<?php\n\nclass Fo...')
#2 /home/james/workspace/better-reflection/test.php(19): PhpParser\Parser\Multiple->parse('<?php\n\nclass Fo...')
#3 {main}
  thrown in /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 280
```

**Comment by nikic** [comment]
Support for class constant visibility added in https://github.com/nikic/PHP-Parser/commit/5ea2a76d8070db1ed33e88322608e51290601931. Structure potentially not final due to #288.
