### ISSUE TITLE
Nullable types are not supported (PHP 7.1 feature)

### ISSUE THREAD

**Issue by asgrim** [nikic/PHP-Parser#286]
Nullable types e.g. `?int` are not supported in PHP-Parser in both `2.1.0` and `dev-master @ 96cbd48`.

https://wiki.php.net/rfc/nullable_types

Isolated example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$c = <<<'PHP'
<?php

class Foo
{
    public function bar(): ?int
    {
        return null;
    }
}
PHP;


use PhpParser\ParserFactory;
$parser = (new ParserFactory)
    ->create(ParserFactory::PREFER_PHP7);

print_r($parser->parse($c));
```

Results in syntax error:

```
PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected '?' on line 5 in /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:280
Stack trace:
#0 /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nclass Fo...')
#1 /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), '<?php\n\nclass Fo...')
#2 /home/james/workspace/better-reflection/test.php(22): PhpParser\Parser\Multiple->parse('<?php\n\nclass Fo...')
#3 {main}
  thrown in /home/james/workspace/better-reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 280
```

**Comment by nikic** [comment]
Tracking bug for PHP 7.1 features: https://github.com/nikic/PHP-Parser/issues/260

I will be working on this soon (next week?), just gotta finish a thesis first.

**Comment by asgrim** [comment]
@nikic Ah, apologies, not sure how I missed that one! Feel free to close both my issues if they don't add any value for you :) thank you.

**Comment by nikic** [comment]
Support for nullable types added with https://github.com/nikic/PHP-Parser/commit/1edf72c0403c451ba9053d2b0ec7c624e16a7645.
