### ISSUE TITLE
Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found

### ISSUE THREAD

**Issue by dugajean** [nikic/PHP-Parser#308]
I have been working on a project which uses this library:

https://github.com/hanneskod/classtools

However, this project uses version ~2.0 and is producing this error anyway:

```
PHP Fatal error:  Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php:2842
Stack trace:
#0 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(247): PhpParser\Parser\Php5->reduceRule476()
#1 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#2 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php5), '<?php\n\nnamespac...')
#3 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Transformer/Reader.php(61): PhpParser\Parser\Multiple->parse('<?php\n\nnamespac...')
#4 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Iterator/SplFileInfo.php(53): hanneskod\classtools\Transformer\Reader->__construct('<?php\n\nnamespac...')
#5 /Users/username/Google D in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 2842

Fatal error: Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php:2842
Stack trace:
#0 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(247): PhpParser\Parser\Php5->reduceRule476()
#1 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#2 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php5), '<?php\n\nnamespac...')
#3 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Transformer/Reader.php(61): PhpParser\Parser\Multiple->parse('<?php\n\nnamespac...')
#4 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Iterator/SplFileInfo.php(53): hanneskod\classtools\Transformer\Reader->__construct('<?php\n\nnamespac...')
#5 /Users/username/projects in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 2842
```

```
PHP 7.0.8 (cli) (built: Jun 23 2016 16:32:40) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

It was working fine last time I checked this project (1 week ago). Now when I got back at it, it keeps spitting this errror.

What could this be? That other package is using the correct package version which should've fixed this problem.

Help would be appreciated.

**Comment by nikic** [comment]
I don't see how this could happen. Version 2.0 uses the composer psr-4 autoloader, so there is none of the fragile class_alias magic of previous versions involved here.

Can you check if the file for this class actually exists in your vendor directory?

**Comment by dugajean** [comment]
Which file do you want me to check exactly?

**Comment by nikic** [comment]
Okay, there's a number of files missing in that directory (String_, LNumber, DNumber). Probably this is just a borked checkout. I'd suggest deleting your vendor/ directory and running composer again and see if this fixes the issue.
