### ISSUE TITLE
Class 'PhpParser\ErrorHandler\Throwing' not found

### ISSUE THREAD

**Issue by PabloJoan** [nikic/PHP-Parser#329]
```
phpdox:
   [phpdox] phpDox 0.8.2-dev - Copyright (C) 2010 - 2016 by Arne Blankerts
   [phpdox] 
   [phpdox] [16.12.2016 - 02:32:00] Using config file './phpdox.xml'
   [phpdox] [16.12.2016 - 02:32:00] Registered collector backend 'parser'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'build'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'git'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'checkstyle'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'phpcs'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'pmd'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'phpunit'
   [phpdox] [16.12.2016 - 02:32:00] Registered enricher 'phploc'
   [phpdox] [16.12.2016 - 02:32:00] Registered output engine 'xml'
   [phpdox] [16.12.2016 - 02:32:00] Registered output engine 'html'
   [phpdox] [16.12.2016 - 02:32:00] Starting to process project 'CafeMedia'
   [phpdox] [16.12.2016 - 02:32:00] Starting collector
   [phpdox] [16.12.2016 - 02:32:00] Scanning directory '../src' for files to process
   [phpdox] 
   [phpdox] 
   [phpdox] 
   [phpdox] Oups... phpDox encountered a problem and has terminated!
   [phpdox] 
   [phpdox] It most likely means you've found a bug, so please file a report for this
   [phpdox] and paste the following details and the stacktrace (if given) along:
   [phpdox] 
   [phpdox] PHP Version: 7.0.14 (Linux)
   [phpdox] PHPDox Version: 0.8.2-dev
   [phpdox] Exception: Error (Code: 0)
   [phpdox] Location: /home/p/.config/composer/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php (Line 28)
   [phpdox] 
   [phpdox] Class 'PhpParser\ErrorHandler\Throwing' not found
   [phpdox] 
   [phpdox] #0 /home/p/.config/composer/vendor/theseer/phpdox/src/collector/Collector.php(141): TheSeer\phpDox\Collector\Backend\PHPParser->parse()
   [phpdox] #1 /home/p/.config/composer/vendor/theseer/phpdox/src/collector/Collector.php(105): TheSeer\phpDox\Collector\Collector->processFile()
   [phpdox] #2 /home/p/.config/composer/vendor/theseer/phpdox/src/Application.php(122): TheSeer\phpDox\Collector\Collector->run()
   [phpdox] #3 /home/p/.config/composer/vendor/theseer/phpdox/src/CLI.php(161): TheSeer\phpDox\Application->runCollector()
   [phpdox] #4 /home/p/.config/composer/vendor/theseer/phpdox/phpdox(67): TheSeer\phpDox\CLI->run()
   [phpdox] 
   [phpdox] 
   [phpdox] 
   [phpdox] Result: 5

```

**Comment by nikic** [comment]
Looks to me like phpDox is using php-parser 3, but you have php-parser 2 installed. Maybe try deleting the vendor/ directory and running composer install again?

**Comment by PabloJoan** [comment]
I think it might be phpDox's problem. https://github.com/theseer/phpdox/issues/289 I'll keep you posted on this issue

**Comment by nikic** [comment]
As this is a 3rd party issue, closing here.
