### ISSUE TITLE
Doesn't support comments outside of namespaces declared with bracketed syntax

### ISSUE THREAD

**Issue by cjohansson** [nikic/PHP-Parser#412]
Comments outside of namespaces defined with brackets seems to crash the parser.

**Steps to reproduce**:
1. Create PHPParser project like this
```
composer require nikic/php-parser
```

2. Create file `testClass.php` like this
```php
<?php

namespace A {
	class MyClassA {
		function myFunctionA() {
			echo "myEchoA";
		}
	}
}

namespace B {
	class MyClassB {
		function myFunctionB() {
			echo "myEchoB";
		}
	}
}

namespace {
	$a = new \A\MyClassA();
	$a->myFunctionA();
	$b = new \B\MyClassB();
	$b->myFunctionB();
	
}

// Test comment
```

3. Create file `test.php`
```php
<?php
require 'vendor/autoload.php';
use PhpParser\ParserFactory;
$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
$code = file_get_contents(__DIR__ . '/testClass.php');
try {
    $stmts = $parser->parse($code);
    // $stmts is an array of statement nodes
} catch (Error $e) {
    echo 'Parse Error: ', $e->getMessage();
}
```

**Expected result**:
It works

**Actual result**:
It fails with error `PHP Fatal error:  Uncaught PhpParser\Error: No code may exist outside of namespace {} on line 19`

**Comment by cjohansson** [comment]
It seems I had a syntax error :(

**Comment by cjohansson** [comment]
Ok I was able to reproduce it now

**Comment by TomasVotruba** [comment]
Hi, could you send failing test to be sure?

**Comment by cjohansson** [comment]
Sure here it is

**Just PHP without PHPParser works:**
```
php -f testClass.php 
myEchoAmyEchoB
```

**With PHPParser, fatal error:**
```
php -f test.php 
PHP Fatal error:  Uncaught PhpParser\Error: No code may exist outside of namespace {} on line 28 in /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:449
Stack trace:
#0 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php(817): PhpParser\ParserAbstract->handleNamespaces(Array)
#1 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(262): PhpParser\Parser\Php7->reduceRule1()
#2 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(50): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...', Object(PhpParser\ErrorHandler\Throwing))
#3 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\n\nnamespac...')
#4 /Users/christianjohansson/Web/PHPParser/test.php(7): PhpParser\Parser\Multiple->parse('< in /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 449

Fatal error: Uncaught PhpParser\Error: No code may exist outside of namespace {} on line 28 in /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:449
Stack trace:
#0 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php(817): PhpParser\ParserAbstract->handleNamespaces(Array)
#1 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(262): PhpParser\Parser\Php7->reduceRule1()
#2 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(50): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...', Object(PhpParser\ErrorHandler\Throwing))
#3 /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\n\nnamespac...')
#4 /Users/christianjohansson/Web/PHPParser/test.php(7): PhpParser\Parser\Multiple->parse('< in /Users/christianjohansson/Web/PHPParser/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 449
```

**Comment by TomasVotruba** [comment]
I meant send PR with test to this project, so we can see build fail. It would be easier to fix then.

Something like this: https://github.com/Roave/BetterReflection/pull/274

**Comment by cjohansson** [comment]
Ok you mean create a unit test for it and do a pull request? All source code is in the first comment, it's not much

**Comment by cjohansson** [comment]
Sure, I can do that later this week if you want

**Comment by TomasVotruba** [comment]
It's better to have (edge) cases covered for future references of the same issues.
Sometimes there is regression bugs and these issues are resend, if not covered with tests.

> Sure, I can do that later this week if you want

That would be great. Just wait for @nikic to confirm, if he needs that.

**Comment by TomasVotruba** [comment]
Thanks @nikic

**Comment by nikic** [comment]
> That would be great. Just wait for @nikic to confirm, if he needs that.

What I mainly care about is having some reproduce code -- it's not so important whether it comes in test form or standalone :)

**Comment by TomasVotruba** [comment]
@nikic I really appreciate your activity around this repo. It's very rare for me to see such active maintainer :bowing_man:
