### ISSUE TITLE
parsing error with named parameters

### ISSUE THREAD

**Issue by mathroc** [nikic/PHP-Parser#698]
when used via PHPUnit for code coverage, I got this error:

```
PhpParser\Error: Syntax error, unexpected ':', expecting ')' on line 57 in /app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:315
Stack trace:
#0 /app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(158): PhpParser\ParserAbstract->doParse()
#1 /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php\n\ndeclare(...', Object(PhpParser\ErrorHandler\Throwing))
#2 /app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing), '<?php\n\ndeclare(...')
#3 /app/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php(126): PhpParser\Parser\Multiple->parse('<?php\n\ndeclare(...')
#4 /app/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php(103): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->analyse('/app/src/Databa...')
#5 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(501): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->ignoredLinesFor('/app/src/Databa...')
#6 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(268): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData))
#7 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(657): SebastianBergmann\CodeCoverage\CodeCoverage->append(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData), 'UNCOVERED_FILES')
#8 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(216): SebastianBergmann\CodeCoverage\CodeCoverage->initializeData()
#9 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(683): SebastianBergmann\CodeCoverage\CodeCoverage->start(Object(Tests\DatabaseQueryTest))
#10 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(880): PHPUnit\Framework\TestResult->run(Object(Tests\DatabaseQueryTest))
#11 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#12 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(671): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(147): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#16 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit\TextUI\Command->run(Array, true)
#17 /app/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#18 {main}

Next SebastianBergmann\CodeCoverage\ParserException: Cannot parse /app/src/Database/DSNHelper.php: Syntax error, unexpected ':', expecting ')' on line 57 in /app/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php:145
Stack trace:
#0 /app/vendor/phpunit/php-code-coverage/src/StaticAnalysis/ParsingCoveredFileAnalyser.php(103): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->analyse('/app/src/Databa...')
#1 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(501): SebastianBergmann\CodeCoverage\StaticAnalysis\ParsingCoveredFileAnalyser->ignoredLinesFor('/app/src/Databa...')
#2 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(268): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData))
#3 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(657): SebastianBergmann\CodeCoverage\CodeCoverage->append(Object(SebastianBergmann\CodeCoverage\RawCodeCoverageData), 'UNCOVERED_FILES')
#4 /app/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(216): SebastianBergmann\CodeCoverage\CodeCoverage->initializeData()
#5 /app/vendor/phpunit/phpunit/src/Framework/TestResult.php(683): SebastianBergmann\CodeCoverage\CodeCoverage->start(Object(Tests\DatabaseQueryTest))
#6 /app/vendor/phpunit/phpunit/src/Framework/TestCase.php(880): PHPUnit\Framework\TestResult->run(Object(Tests\DatabaseQueryTest))
#7 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#8 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(665): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 /app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(671): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(147): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#12 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit\TextUI\Command->run(Array, true)
#13 /app/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#14 {main}

Next PHPUnit\TextUI\Exception: Cannot parse /app/src/Database.php: Syntax error, unexpected ':', expecting ')' on line 57 in /app/vendor/phpunit/phpunit/src/TextUI/Command.php:102
Stack trace:
#0 /app/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#1 {main}
```

This is the code causing the error (line 57 of the /app/src/Database.php)

```php
return new \PDO($dsn, options: $options,);
```

**Comment by nikic** [comment]
This was supported but not released yet. Now done with https://github.com/nikic/PHP-Parser/releases/tag/v4.9.0.
