### ISSUE TITLE
Fatal Error in ParserAbstract.php

### ISSUE THREAD

**Issue by Raghu-Kanchiraju** [nikic/PHP-Parser#717]
This is the stack trace generated:
```
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ',' or ']' or ')' on line 160 in phar:///Users/developer/Desktop/project/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:266
Stack trace:
#0 phar:///Users/developer/Desktop/project/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(142): PhpParser\ParserAbstract->doParse()
#1 phar:///Users/developer/Desktop/project/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(48): PhpParser\ParserAbstract->parse('<?php\n/**\n * DE...', Object(PhpParser\ErrorHandler\Throwing))
#2 phar:///Users/developer/Desktop/project/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Throwing in phar:///Users/developer/Desktop/project/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 266
```

I think this is independent of application code or the environment. Let me know otherwise.

**Comment by Raghu-Kanchiraju** [comment]
We are on v4.10.1

**Comment by nikic** [comment]
PhpParser\Error indicates a syntax error in the *parsed* code. The error message says it occurs on line 160 of whatever you're parsing, but the PHP-Parser library doesn't know which file that is (only the calling code can know that).
