### ISSUE TITLE
Adding item to array when trying to preserve format throws AssertionError

### ISSUE THREAD

**Issue by ramsey** [nikic/PHP-Parser#813]
l'm trying to add an item to an array using code similar to the following:

```php
<?php

require_once 'vendor/autoload.php';

use PhpParser\{Lexer, Node, NodeTraverser, NodeVisitor, NodeVisitorAbstract, Parser, PrettyPrinter};

$code = <<<'CODE'
    <?php

    $formatter = new Formatter();

    $formatter->formatMessage([
        'defaultMessage' => 'Today is {ts, date, ::yyyyMMdd}',
    ], ['ts' => time()]);
    CODE;

$lexer = new Lexer\Emulative(['usedAttributes' => ['comments', 'startLine', 'endLine', 'startTokenPos', 'endTokenPos']]);
$parser = new Parser\Php7($lexer);

$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeVisitor\CloningVisitor());
$traverser->addVisitor(new class extends NodeVisitorAbstract {
    public function enterNode(Node $node): void
    {
        if ($node instanceof Node\Expr\MethodCall && $node->name->name === 'formatMessage') {
            $node->args[0]->value->items[] = new Node\Expr\ArrayItem(
                new Node\Scalar\String_('foobar'),
                new Node\Scalar\String_('id'),
            );
        }
    }
});

$oldStatements = $parser->parse($code);
$oldTokens = $lexer->getTokens();
$newStatements = $traverser->traverse($oldStatements);

$printer = new PrettyPrinter\Standard();
$newCode = $printer->prettyPrintFile($newStatements);
//$newCode = $printer->printFormatPreserving($newStatements, $oldStatements, $oldTokens);

echo "$newCode\n"
```

When I execute this with `prettyPrintFile()`, I get the following, as expected:

```php
<?php

$formatter = new Formatter();
$formatter->formatMessage(['defaultMessage' => 'Today is {ts, date, ::yyyyMMdd}', 'id' => 'foobar'], ['ts' => time()]);
```

However, when I execute it with `printFormatPreserving()`, I get an AssertionError:

```
PHP Fatal error:  Uncaught AssertionError: assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos) in /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:759
Stack trace:
#0 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(759): assert(false, 'assert($itemSta...')
#1 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 24, 0, 'Expr_Array', 'items', NULL)
#2 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(670): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\Array_), true)
#3 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(896): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Arg), true)
#4 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 16, 0, 'Expr_MethodCall', 'args', NULL)
#5 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(670): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\MethodCall), true)
#6 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(896): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)
#7 /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(492): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 12, 0, 'File', 'stmts', NULL)
#8 /Users/ramsey/Developer/sandbox/foo/baz.php(40): PhpParser\PrettyPrinterAbstract->printFormatPreserving(Array, Array, Array)
#9 {main}
  thrown in /Users/ramsey/Developer/sandbox/foo/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php on line 759
```

Is there a way to add nodes while preserving the format?

I've also tried replacing existing array items, as well as using method arguments instead of arrays and replacing the arguments, but all of my attempts result in the same error.

**Comment by ramsey** [comment]
I figured out my problem. I needed to use a separate traverser to modify the statements.

Here's the code that works. In this code, I named my separate traverser `$modifyingTraverser`.

```php
<?php

require_once 'vendor/autoload.php';

use PhpParser\{Lexer, Node, NodeTraverser, NodeVisitor, NodeVisitorAbstract, Parser, PrettyPrinter};

$code = <<<'CODE'
    <?php

    $formatter = new Formatter();

    $formatter->formatMessage([
        'defaultMessage' => 'Today is {ts, date, ::yyyyMMdd}',
    ], ['ts' => time()]);
    CODE;

$lexer = new Lexer\Emulative(['usedAttributes' => ['comments', 'startLine', 'endLine', 'startTokenPos', 'endTokenPos']]);
$parser = new Parser\Php7($lexer);

$traverser = new NodeTraverser();
$traverser->addVisitor(new NodeVisitor\CloningVisitor());

$oldStatements = $parser->parse($code);
$oldTokens = $lexer->getTokens();
$newStatements = $traverser->traverse($oldStatements);

$modifyingTraverser = new NodeTraverser();
$modifyingTraverser->addVisitor(new class extends NodeVisitorAbstract {
    public function enterNode(Node $node)
    {
        if ($node instanceof Node\Expr\MethodCall && $node->name->name === 'formatMessage') {
            $node->args[0]->value->items[] = new Node\Expr\ArrayItem(
                new Node\Scalar\String_('foobar'),
                new Node\Scalar\String_('id'),
            );

            return $node;
        }
    }
});

$newStatements = $modifyingTraverser->traverse($newStatements);

$printer = new PrettyPrinter\Standard();
//$newCode = $printer->prettyPrintFile($newStatements);
$newCode = $printer->printFormatPreserving($newStatements, $oldStatements, $oldTokens);

echo "$newCode\n";
```

It prints out:

```php
<?php

$formatter = new Formatter();

$formatter->formatMessage([
    'defaultMessage' => 'Today is {ts, date, ::yyyyMMdd}', 'id' => 'foobar',
], ['ts' => time()]);
```
